version: '3.8'

services:
 kafka:
   image: confluentinc/cp-kafka:latest
   container_name: monitoring-kafka
   ports:
     - "9092:9092"
   environment:
     CLUSTER_ID: "monitoring-kafka-cluster-1"
     KAFKA_NODE_ID: 1
     KAFKA_PROCESS_ROLES: 'broker,controller'
     KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:9093'
     KAFKA_LISTENERS: 'PLAINTEXT://:9092,CONTROLLER://:9093'
     KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:9092'
     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT'
     KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
     KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
     KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
   volumes:
     - kafka_data:/var/lib/kafka/data
   healthcheck:
     test: nc -z localhost 9092 || exit 1
     interval: 10s
     timeout: 5s
     retries: 5

 php-web:
   build:
     context: ./php
     dockerfile: Dockerfile
   container_name: monitoring-php
   volumes:
     - ./php:/var/www/html
     - /var/run/docker.sock:/var/run/docker.sock
   ports:
     - "8083:80"
   environment:
     MONGODB_URI: "mongodb+srv://stradivirus:1q2w3e4r@cluster0.e7rvfpz.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
     KAFKA_BROKER: "kafka:9092"
     DOCKER_HOST: "unix:///var/run/docker.sock"
     PHP_INI_MEMORY_LIMIT: "512M"
   depends_on:
     kafka:
       condition: service_healthy
   command: >
     sh -c "composer install --no-dev --optimize-autoloader &&
            chmod 666 /var/run/docker.sock &&
            sed -i 's#DocumentRoot /var/www/html#DocumentRoot /var/www/html/src/api#' /etc/apache2/sites-available/000-default.conf &&
            apache2-foreground"
   restart: unless-stopped

 collector:
   build:
     context: ./php
     dockerfile: Dockerfile
   container_name: monitoring-collector
   volumes:
     - ./php:/var/www/html
     - /var/run/docker.sock:/var/run/docker.sock
   environment:
     MONGODB_URI: "mongodb+srv://stradivirus:1q2w3e4r@cluster0.e7rvfpz.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
     KAFKA_BROKER: "kafka:9092"
     DOCKER_HOST: "unix:///var/run/docker.sock"
     PHP_INI_MEMORY_LIMIT: "512M"
   depends_on:
     kafka:
       condition: service_healthy
   command: >
     sh -c "composer install --no-dev --optimize-autoloader &&
            chmod 666 /var/run/docker.sock &&
            php src/collect.php"
   restart: unless-stopped

 frontend:
   build:
     context: ./frontend
     dockerfile: Dockerfile
   container_name: monitoring-frontend
   volumes:
     - ./frontend:/app
     - /app/node_modules
   ports:
     - "5173:5173"
   environment:
     - VITE_API_URL=http://localhost:8083
   depends_on:
     - php-web
   networks:
     - default
   restart: unless-stopped
   command: npm run dev -- --host

volumes:
 kafka_data:

networks:
 default:
   name: monitoring-network